// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARUXX_k74WEz-ESdkyUKIxAI95a4KB7Js',
    appId: '1:417119237800:android:65928d6e406eb13001749d',
    messagingSenderId: '417119237800',
    projectId: 'ledgify-ukdev',
    storageBucket: 'ledgify-ukdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhhCDxZj7hc7RCsWQAoV_tFUfBkUzoMKo',
    appId: '1:417119237800:ios:d11286bc1211a91001749d',
    messagingSenderId: '417119237800',
    projectId: 'ledgify-ukdev',
    storageBucket: 'ledgify-ukdev.firebasestorage.app',
    androidClientId: '417119237800-sv5ntd77bfhqgg9oapi8mifp22mqqd29.apps.googleusercontent.com',
    iosClientId: '417119237800-20uic9j14grubop7k042v4qckiou5f4q.apps.googleusercontent.com',
    iosBundleId: 'com.ukdev.ledgify',
  );
}
